### ISSUE TITLE
Auth0 jwt validation error

### ISSUE THREAD

**Issue by GaoWhitebird** [IronCoreLabs/ironoxide-swift#56]
if let ironJwt = Jwt(auth0IdToken) {
                print(ironJwt)
            }

This is showing error like this :

"\'jwt\' failed validation with the error \'JSON error: missing field `pid` at line 1 column 543\'"

**Comment by giarc3** [comment]
You can read the requirements for jwt in the JwtClaims [documentation](https://ironcorelabs.github.io/ironoxide-swift/Classes/JwtClaims.html) to see the required fields. As this repo is ultimately derived from the Rust repo IronCoreLabs/ironoxide, more complete documentation can be found [here](https://docs.rs/ironoxide/latest/ironoxide/user/struct.JwtClaims.html) and an example of a valid jwt can be found in tests [here](https://github.com/IronCoreLabs/ironoxide/blob/main/src/internal/user_api.rs#L906). 
I apologize for the lack of clarity in this repo, so please let me know if you need additional information.

**Comment by GaoWhitebird** [comment]
fn valid_jwt_namespace_construction() {
        // This is a JWT with the following claims (generated by Auth0):
        // { "http://ironcore/pid": 1, "http://ironcore/kid": 1859, "http://ironcore/sid": "IronHide",
        //    "http://ironcore/uid": "bob.wall@ironcorelabs.com", "iss": "https://ironcorelabs.auth0.com/",
        //    "sub": "github|11368122", "aud": "hGELxuBKD64ltS4VNaIy2mzVwtqgJa5f", "iat": 1593130255, "exp": 1593133855 }
        let jwt = Jwt::try_from("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlEwWXhNekUwTlVJeE9UVTNRakZFTlRZM01rVkNRakE0UkVNMk1UTkZOVGRETVRBNE9EQTVNUSJ9.eyJodHRwOi8vaXJvbmNvcmUvcGlkIjoxLCJodHRwOi8vaXJvbmNvcmUva2lkIjoxODU5LCJodHRwOi8vaXJvbmNvcmUvc2lkIjoiSXJvbkhpZGUiLCJodHRwOi8vaXJvbmNvcmUvdWlkIjoiYm9iLndhbGxAaXJvbmNvcmVsYWJzLmNvbSIsImlzcyI6Imh0dHBzOi8vaXJvbmNvcmVsYWJzLmF1dGgwLmNvbS8iLCJzdWIiOiJnaXRodWJ8MTEzNjgxMjIiLCJhdWQiOiJoR0VMeHVCS0Q2NGx0UzRWTmFJeTJtelZ3dHFnSmE1ZiIsImlhdCI6MTU5MzEzMDI1NSwiZXhwIjoxNTkzMTMzODU1fQ.Y3DsoS-TctytMNpEFnewJ5TT33yRblRmNkNPIQ2EDmfka070y5egpMsVtjqqck05cpdShxfZG2n2JWr5LQF6--jEa8mHy73V36ZbBHkcvjhEcHdH3OxhQQPUNwrXN-jIFOD58G7K5ZNCZub8IsEpWPD8PwghWlwiLKSFMb_j12SEs1rQwoVs1NaYsVZk04G6fWwooyrpuulXVc6S8g8Cr6_FeHDkb8747UY2GmL3Qp0R3iCPjao0ESSqP9gwPMroQGiNhjfJhYwxM8_sin4skfWoEirj0IRk2M8LAEOszI6gTdMcFX8Bw-0kFw4LWYBOi1eHcmvzNFMgCJUB5I4rcg");
        assert!(jwt.is_ok())
    }




I have tried in swift but result is the same. It is showing error.

**Comment by giarc3** [comment]
@GaoWhitebird that is strange. I went ahead and added that JWT string as a test in this repo [here](https://github.com/IronCoreLabs/ironoxide-swift/blob/main/Tests/IronOxideTests/CommonStructsTests.swift#L71) and it seems to pass. Please consider updating to the latest version of the library and running the tests and maybe that will give us more information to go off of.

**Comment by GaoWhitebird** [comment]
Thanks
