### ISSUE TITLE
Version upgrade to last

### ISSUE THREAD

**Issue by BaiXiaoYan** [IronCoreLabs/ironoxide-swift#57]
ironoxide-swift library does not support ironoxide-swig-bindings v0.14.7.
Please update this library for supporting ironoxide-swig-bindings v0.14.7.

**Comment by giarc3** [comment]
Hi @BaiXiaoYan, thank you for bringing this to my attention. I've gone ahead and released a new version of ironoxide-swift that depends on v0.14.7. Please try it out and let me know if you have any issues.

**Comment by BaiXiaoYan** [comment]
@giarc3

Social login 


"\'jwt\' failed validation with the error \'JSON error: duplicate field `sid` at line 1 column 780\'"
