### ISSUE TITLE
Auth0 jwt error

### ISSUE THREAD

**Issue by BaiXiaoYan** [IronCoreLabs/ironoxide-swift#61]
@giarc3

let jwt = Jwt(auth0token)

Getting below error for Social logins(facebook and google)

"\'jwt\' failed validation with the error \'JSON error: duplicate field `sid` at line 1 column 780\'"

_Originally posted by @BaiXiaoYan in https://github.com/IronCoreLabs/ironoxide-swift/issues/57#issuecomment-1237524624_

**Comment by giarc3** [comment]
An issue with more detail has been created here https://github.com/IronCoreLabs/ironoxide/issues/280

**Comment by BaiXiaoYan** [comment]
@giarc3
I've seen you updated ironoxide library.
Can I get update of ironoxide-swift library please?
Thanks.

**Comment by giarc3** [comment]
@BaiXiaoYan 
This is currently being review in https://github.com/IronCoreLabs/ironoxide-swift/pull/62

**Comment by giarc3** [comment]
ironoxide-swift v0.16.0 has now been released. Please let me know if you continue to have issues with auth0 JWTs after consuming this change.
